### ISSUE TITLE
Keep template's model.js mostly empty? 

### ISSUE THREAD

**Issue by rgwozdz** [koopjs/koop-cli#24]
My own preference would be to remove most of the sample code (https://github.com/koopjs/koop-cli/blob/master/src/templates/provider/project/src/model.js#L54-L77) from model.js.  It's a good illustration of a typical provider, but in practice I have to go and delete/cleanup this code when I use cli to spin up new provider boilerplate. 

Can we have another provider template choice that omits this code?

**Comment by haoliangyu** [comment]
That's a good point. This code does not provide much practical benefit to the developer. Adding a new provider template choice (just for education or showcase) may result in confusion. I think it is better to add a link to the https://github.com/koopjs/koop-provider-sample in the comment or README, then remove the code example.
