### ISSUE TITLE
Debug with visual studio

### ISSUE THREAD

**Issue by hhkaos** [koopjs/koop-cli#38]
@haoliangyu how do you setup Visual Studio or use `node --inspect --debug-brk` when debugging a new provider? I'm running `koop serve` but I don't know how to debug it.

Thanks!

**Comment by haoliangyu** [comment]
This is not available now. It is simply running `node src/index.js` and does not inject parameters (see https://github.com/koopjs/koop-cli/blob/master/src/utils/serve/index.js#L13). It can be a next feature.

**Comment by hhkaos** [comment]
I agree, actually I think it is very important if we want to build a community around Koop, first of all we need to take care of the developer experience first: good documentation and developer tools should come first, right? With the new documentation page and koop-cli we are in the right direction! :+1: I will [continue spreading the word](https://docs.google.com/presentation/d/1DDe5hLrf4L17s_xrhLKTiDWnrv8cL9iAzdOyl6KpHao/edit?usp=sharing) about Koop :)

**Comment by haoliangyu** [comment]
@hhkaos I have released a new version (v0.6.0). Now you can use `koop serve --debug` to enable the nodejs inspector. It uses the default hostname and port. This works with Chrome DevTool.

**Comment by hhkaos** [comment]
Awesome!! thx! I'll try it asap :heart_eyes:
