### ISSUE TITLE
Release for koop v4

### ISSUE THREAD

**Issue by gavinr** [koopjs/koop-cli#48]
When I follow the instructions on https://koopjs.github.io/docs/basics/quickstart#using-the-koop-cli, it installs an app that is using koop v3:

![image](https://user-images.githubusercontent.com/209355/88936138-1645cf80-d272-11ea-80fb-14c5dc34c2f2.png)

... but [v4 has been out for a month](https://koopjs.github.io/blog/2020/07/01/koop-v-4-0-0/). I see you [updated the master branch](https://github.com/koopjs/koop-cli/commit/a4570684f854334b071a3a31b2ce342061211002#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34), but can we do a release so when I install koop-cli from npm I get the latest koop? Thanks!

**Comment by haoliangyu** [comment]
Thanks for pointing this out. We can definitely release an update today or tomorrow.

**Comment by gavinr** [comment]
thanks!

**Comment by haoliangyu** [comment]
Please check the latest version (v0.6.3) and it should generate projects using Koop v4.

**Comment by gavinr** [comment]
Thank you!
